"""Add language support?

Revision ID: 6f299cb27481
Revises: 4a1d339bf7d7
Create Date: 2021-04-05 09:34:53.122198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f299cb27481'
down_revision = '4a1d339bf7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'language')
    # ### end Alembic commands ###
