"""Add background jobs

Revision ID: 765ad07bb9ae
Revises: c2f206bf7135
Create Date: 2021-04-10 13:53:25.138441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765ad07bb9ae'
down_revision = 'c2f206bf7135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_name'), 'job', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_name'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
